import beach from "../../assets/Gallery/beach.jpeg";
import forest from "../../assets/Gallery/forest.jpeg";
import mount from "../../assets/Gallery/mount.jpeg";
import tajmahal from "../../assets/Gallery/tajmahal.jpeg";
import springHiking from "../../assets/Gallery/springHiking.jpeg";
import maldives from "../../assets/Gallery/maldives.jpeg";
import resting from "../../assets/Gallery/resting.jpeg";

const travelData = [
  {
    id: 1,
    title: "Thailand",
    subtitle: "Beach in February",
    image: beach,
    description:
      "Enjoy the warm waters and scenic coastlines of Thailand in February.",
    location: "Satara, India",
    coordinates: { lat: 17.6805, lng: 73.9933 },
    duration: "5 Days / 4 Nights",
    day: "15 days",
    age: "20+ Ages",
    price: "$899",
    food: "Buffet breakfast and seafood dinners included",
    stay: "4-star beachside resort with sea view rooms",
    activities: "Snorkeling, beach volleyball, island hopping",
    departureTime: "9:00 AM",
    dressCode: "Beachwear and casual",
    included: "✅Accommodation, ✅Meals, ✅Local Guide,✅ Airport Transfer",
    notIncluded: "❌Flights, ❌Personal Expenses",
    tourPlan: [
      "Arrival and welcome dinner",
      "Island hopping tour",
      "Water sports and spa",
      "Leisure and sunset cruise",
      "Departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: beach, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 2,
    title: "Forest Adventure",
    subtitle: "Just Beautiful",
    image: forest,
    description:
      "Wander through lush forests filled with wildlife and tranquility.",
    location: "Black Forest, Germany",
    coordinates: { lat: 48.017, lng: 8.209 },
    duration: "3 Days / 2 Nights",
    day: "3 days",
    age: "18+ Ages",
    price: "$499",
    food: "Traditional German meals",
    stay: "Cabin in the woods",
    activities: "Hiking, bird watching, forest photography",
    departureTime: "8:00 AM",
    dressCode: "Comfortable hiking attire",
    included: "✅Accommodation, ✅Meals, ✅Local Guide",
    notIncluded: "❌Travel Insurance, ❌Flights",
    tourPlan: [
      "Arrival and forest hike",
      "Nature walk and photography",
      "Bird watching and departure",
    ],
    ratings: {
      accommodation: 9,
      meals: 4,
      overall: 6,
      transport: 4,
      "value for money": 8,
    },
    galleryImages: [
      { src: mount, alt: "Thailand Beach 1" },
      { src: beach, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 3,
    title: "Mountains",
    subtitle: "Explore the Beauty",
    image: mount,
    description: "Experience the peace and adventure of high-altitude hiking.",
    location: "Swiss Alps",
    coordinates: { lat: 46.8182, lng: 8.2275 },
    duration: "7 Days / 6 Nights",
    day: "7 days",
    age: "16+ Ages",
    price: "$1,299",
    food: "Mountain lodge cuisine",
    stay: "Alpine huts",
    activities: "Hiking, climbing, stargazing",
    departureTime: "7:30 AM",
    dressCode: "Thermal wear and boots",
    included: "✅Accommodation, ✅Meals, ✅Climbing Gear, ✅Guide",
    notIncluded: "❌Travel Insurance",
    tourPlan: [
      "Arrival and acclimatization",
      "Guided mountain hike",
      "Climbing expedition",
      "Stargazing night",
      "Rest and explore nearby village",
      "Hike back",
      "Departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: beach, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 4,
    title: "Taj Mahal",
    subtitle: "Explore the Beauty",
    image: tajmahal,
    description: "Witness the timeless beauty of this iconic symbol of love.",
    location: "Vishal Nagar, India",
    coordinates: { lat: 27.1751, lng: 78.0421 },
    duration: "2 Days / 1 Night",
    day: "2 days",
    age: "All Ages",
    price: "$199",
    food: "Indian thali meals",
    stay: "City hotel",
    activities: "Taj Mahal visit, local sightseeing",
    departureTime: "10:00 AM",
    dressCode: "Modest casual",
    included: "✅Hotel, ✅Meals, ✅Entry tickets",
    notIncluded: "❌Transport to Agra",
    tourPlan: [
      "Arrival and local market visit",
      "Taj Mahal Visit",
      "Departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: tajmahal, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 5,
    title: "Spring Hiking",
    subtitle: "Just Beautiful",
    image: springHiking,
    description:
      "Breathe in the fresh air and enjoy colorful blooms on the trail.",
    location: "Rocky Mountains, USA",
    coordinates: { lat: 39.5501, lng: -105.7821 },
    duration: "4 Days / 3 Nights",
    day: "4 days",
    age: "15+ Ages",
    price: "$699",
    food: "Picnic-style meals",
    stay: "Mountain lodges",
    activities: "Hiking, nature photography",
    departureTime: "6:30 AM",
    dressCode: "Layered hiking wear",
    included: "✅Meals, ✅Accommodation, ✅Guide",
    notIncluded: "❌Flights",
    tourPlan: [
      "Arrival and orientation",
      "Spring trail hike",
      "Photography and local wildlife",
      "Departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: tajmahal, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 6,
    title: "Maldives Getaway",
    subtitle: "Explore the Beauty",
    image: maldives,
    description: "Relax in the crystal-clear waters and white sandy beaches.",
    location: "Maldives",
    coordinates: { lat: 3.2028, lng: 73.2207 },
    duration: "6 Days / 5 Nights",
    day: "6 days",
    age: "21+ Ages",
    price: "$1,499",
    food: "Seafood and continental meals",
    stay: "Luxury overwater villas",
    activities: "Scuba diving, spa, sunbathing",
    departureTime: "10:30 AM",
    dressCode: "Tropical beachwear",
    included: "✅Meals, ✅Accommodation, ✅Activities",
    notIncluded: "❌International Flights",
    tourPlan: [
      "Arrival and resort check-in",
      "Scuba diving session",
      "Spa and relaxation",
      "Island exploration",
      "Free leisure day",
      "Departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: tajmahal, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 7,
    title: "Tropical Escape",
    subtitle: "Explore the Beauty",
    image: maldives,
    description: "Unwind in an overwater villa with ocean views.",
    location: "Maldives",
    coordinates: { lat: 3.2028, lng: 73.2207 },
    duration: "5 Days / 4 Nights",
    day: "5 days",
    age: "Adults Only",
    price: "$1,299",
    food: "All-inclusive buffet",
    stay: "Private villa",
    activities: "Snorkeling, kayaking",
    departureTime: "11:00 AM",
    dressCode: "Casual resort wear",
    included: "✅Meals, ✅Accommodation, ✅Water Sports",
    notIncluded: "❌Flights, ❌Alcohol",
    tourPlan: [
      "Arrival and welcome drink",
      "Snorkeling and beach relaxation",
      "Kayaking and photo ops",
      "Leisure day",
      "Departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: tajmahal, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 8,
    title: "Resting on the Beach",
    subtitle: "Just Beautiful",
    image: resting,
    description: "Feel the breeze while resting under a palm tree by the sea.",
    location: "Goa, India",
    coordinates: { lat: 15.2993, lng: 74.124 },
    duration: "3 Days / 2 Nights",
    day: "3 days",
    age: "All Ages",
    price: "$299",
    food: "Goan cuisine",
    stay: "Beach huts",
    activities: "Swimming, sunbathing",
    departureTime: "9:30 AM",
    dressCode: "Light beach clothes",
    included: "✅Accommodation, ✅Meals",
    notIncluded: "❌Transport, ❌Drinks",
    tourPlan: [
      "Arrival and beach walk",
      "Sunbathing and swimming",
      "Local food tasting and departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: tajmahal, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 9,
    title: "City Lights",
    subtitle: "Urban Charm",
    image: "", // You can replace with actual image if available
    description: "Explore bustling city life and vibrant night scenes.",
    location: "New York City, USA",
    coordinates: { lat: 40.7128, lng: -74.006 },
    duration: "4 Days / 3 Nights",
    day: "4 days",
    age: "18+ Ages",
    price: "$799",
    food: "Variety of local and international cuisine",
    stay: "Downtown hotel",
    activities: "Sightseeing, nightlife",
    departureTime: "10:00 AM",
    dressCode: "City casual",
    included: "✅Hotel, ✅City Tour",
    notIncluded: "❌Flights, ❌Meals",
    tourPlan: [
      "Arrival and Times Square",
      "City tour and Central Park",
      "Museum visit and Broadway show",
      "Departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: tajmahal, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 10,
    title: "Desert Safari",
    subtitle: "Adventure Awaits",
    image: "",
    description: "Ride across golden dunes and enjoy desert camp experiences.",
    location: "Dubai, UAE",
    coordinates: { lat: 25.2048, lng: 55.2708 },
    duration: "2 Days / 1 Night",
    day: "2 days",
    age: "16+ Ages",
    price: "$499",
    food: "BBQ dinner and breakfast",
    stay: "Desert camp",
    activities: "Dune bashing, camel riding, belly dance",
    departureTime: "3:00 PM",
    dressCode: "Comfortable desert wear",
    included: "✅Safari, ✅Meals, ✅Camp Stay",
    notIncluded: "❌International Flights",
    tourPlan: [
      "Arrival and dune bashing",
      "BBQ dinner and cultural show",
      "Sunrise camel ride and departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: tajmahal, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
  {
    id: 11,
    title: "Northern Lights",
    subtitle: "Magical Nights",
    image: "",
    description: "Watch the sky dance with vibrant colors during winter.",
    location: "Tromsø, Norway",
    coordinates: { lat: 69.6496, lng: 18.956 },
    duration: "5 Days / 4 Nights",
    day: "5 days",
    age: "All Ages",
    price: "$1,099",
    food: "Local cuisine",
    stay: "Glass igloo or cabin",
    activities: "Aurora hunting, dog sledding",
    departureTime: "7:00 PM",
    dressCode: "Thermal layers",
    included: "✅Stay, ✅Aurora Tour, ✅Breakfast",
    notIncluded: "❌Flights, ❌Winter Gear",
    tourPlan: [
      "Arrival and orientation",
      "Aurora borealis viewing",
      "Dog sledding and snow fun",
      "Northern culture exploration",
      "Departure",
    ],
    ratings: {
      accommodation: 8,
      meals: 7,
      overall: 8.5,
      transport: 9,
      "value for money": 8,
    },
    galleryImages: [
      { src: tajmahal, alt: "Thailand Beach 1" },
      { src: mount, alt: "Thailand Beach 2" },
    ],
  },
];

export default travelData;
